sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: qSaOSh11WpZITZjBvs0da1EfIgpCj3Yk4GvggfBngUPNu+ZAiQn6MN0ELuwf0b9Bt3T++p++7RgCQS3IAC45SV25cN0KQ9a7rc3RS6uczybyoFS6BFzQLwe66YcSgujZ24FmpOF+bjo9R4OREIzj0ZCNJcZmqA/ZAMqXWPmq2dzN+2TS7zqjFigYajPKU0/rWsCVneQeDhE1hi02vc8hot2DfGVUzW7FKlRtgQcFGTdxPmY34u6/KYQ6ey8saSPJ94znIJKm8JzeD5Q5KTBPXDM+ibZrlB5qHDD7xB3iCn1BqZTmF/ZlcoN3uKkr57HpODwzqpWPrNmFoP5Z4tk3fVW2ynzs81NgXZSDHzD3Bb8Llsee/8+RJgT+nYoPyfGfJqKoflHUgXvI3Oy1cbxAhPaqdWH6qe9mhqk9K80yzP1Ne3Zls6A/j/zCoDm7SgrTM+d7786VG1OS2qhuFiiVwD5mOARk5TuaSqvlAZBmie+k3XPnL4D24fPWa4ZPJV2yUs8wty48pPi9E0TH6158NCWBpX2S2FHXti1fjg+NEq4hGU2aCFlQpoiYMQDKez2S3euZsTyj3L05njgHxMFybsIVhhJ9Jqqha5tSDBdhtslw61M1UBS1573oxT/85wWSSHMOrCxe0zt/lqPrf256PUQ9R6UZ3cM1QeDnhBzqZoQ=
  - secure: Jw2Zu+tw5PUmkRQnM26DqVPfgWrFNt4yxrjGEyu46TrpZ/XHJq3f/bN8XHIUHJP4IOctduL0oZN8QtTpKF94vwqmSLTdJcMTxtD/d/q9NgkLKuuOy5BY0F4Y8LX6ysj5NVcnTfCGTyYvuIoM+AV/DXxBAfNdnLHfGqrKtSalnkLpfyarCvvjjXqAt+LjWKA2aVYIFOkrGi5ysZcl2xWbUMAgzS2T0GfmR+Y3wtZEc2fCcjSXRiuzMu6eTa8OQtdnCGLuVEeKO3Qtr4rrDQV+Mn1eQ0pgnyY5qNhL4RV3AIgSiagp9MTzPjOwUb8Gg14puvPmkEerf/XeARhzZ2e4W5LRn92w1nSqpePybVoYVF5SBn5Bgal8FIwxOVFsElRhc+hHeiu4RaUidY08bXJEatP/Lzs4YV9IWFRAl2ndU9d46WyFZ6+Fz5WPenjGxRQd20qcSQ/rnB+V5HnzLtfRNsKtDK3cpQQ2s0qDsKufHyNk9JTHA+EqTPg5wt+LJmcbloCYcyj+J5OAjakwgrSgVwf7NaAhR2cNZJioW5HRyRiua/eF5cAziVyyijRJjC08DYuQAAqph3c2mzrqRAtCaXPnzNUlseegDxYYmAt5qHKgJsbG4Uo5qSzZxjd9xK4zYMyKJ+8RgvjSmHPEA/fuifwW7ZPpjwfU7EGtlyKH3rE=
